/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lab05_pop_ArrayJNIApp */

#ifndef _Included_lab05_pop_ArrayJNIApp
#define _Included_lab05_pop_ArrayJNIApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lab05_pop_ArrayJNIApp
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lab05_1pop_ArrayJNIApp_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
